# -*- coding: utf-8 -*-
"""Qualité des données.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RqnuIcve6ycTEHHpJqjpy7hkMMzhEq4D
"""

import pandas as pd
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
df = pd.read_excel(r'data/Climat.xlsx', skiprows = 2,  nrows= 32, usecols = 'C:O')
df = df.drop(df.index[0])
df.drop(df.columns[0], axis=1, inplace=True)
df

print(" *** Moyenne : *** ")
average=[]
for index,m in enumerate (df.columns.values,start=0):
  average.append(df.aggregate({m:np.mean}).values)
  print(m + ' : ', average[index])

print(" *** Ecart type : *** ")
ecart_type=[]
ecart_type.append(df.std())
print(ecart_type)

print(" *** Min par mois: *** ")
min_per_month=[]
for index,column in enumerate (df,start=0):
  min_per_month.append(df[column].min())
  print(column +" : " +str(min_per_month[index]))

print(" *** Min par années: *** ")
min_year= min(min_per_month)
print(min_year)

print(" *** Max par mois: *** ")
max_per_month=[]
for index,column in enumerate (df,start=0):
  max_per_month.append(df[column].max())
  print(column +" : " +str(max_per_month[index]))

print(" *** Max par années: *** ")
max_year= max(max_per_month)
print(max_year)

#for column in df:
#  plt.plot(df[column])
#  plt.ylabel(column)
#  plt.show()

year=pd.DataFrame(columns=['Temperature'])

for column in df:
  for day in df[column]:
    year = year.append({'Temperature':day},ignore_index=True)
    year = year.dropna()
year

for column in year:
  plt.figure(figsize=(10,10))
  plt.plot(year[column])
  plt.ylabel(column)
plt.show()

